### ISSUE TITLE
Codificación de la API CRM

### ISSUE THREAD

**Issue by BassedWarrior** [BassedWarrior/TC2007B.401#11]
Codificación de los endpoints de la API del CRM para comunicar front-end de
react-admin con mongodb.

## Endpoints de recursos

- [x] Endpoints de recurso de donadores. Completed with #26.
    - GET
    - POST
    - PUT
- [x] Endpoints de recurso de donadores. Completed with #26.
    - GET
    - POST
    - PUT
- [x] Endpoints de recurso de proyectos. Pending completion with #29.
    - GET
    - POST
    - PUT
- [x] Endpoints de recurso de administradores. Completed with #21.
    - GET
    - POST
    - PUT

## Endpoints de seguridad

- [x] Endpoints de login. Pending completion with #25.
    - POST
